### ISSUE TITLE
18228 - Build a LAMP stack for Python - Ubuntu, Debian

### ISSUE THREAD

**Issue by susankayjordan** [gnakan/gd-cloud-docs#53]

**Comment by susankayjordan** [comment]
Fixed errors
added ordered list 
etc...

**Comment by CrystalSmithwick** [comment]
BLOCKING QUESTIONS - Is the use of Ubuntu Linux correct?   Replacing external installation links with internal.

NOTES (Partial - will continue when questions are answered.)
 - Use of 'which" vs "that
 - Do not include the word "step" and a number in a heading.  Order and heading hierarchy determine.  If you are concerned about specific order, you can include a summary of the steps in the introduction.
 - Use the second person "you" instead of "we," unless the "we refers to the writer of the article.  "In this article, we are using "GoDaddy" as an example. You will replace those references with your company name."

**Comment by cjamesbpcs** [comment]
I have corrected what I could, I am moving to ready for code for Susan so she can correct or give me the code to correct certain XHTML issues within the article.

**Comment by susankayjordan** [comment]
Cleaned the HTML  Code Validated

**Comment by CrystalSmithwick** [comment]
BLOCKED Still missing links.  Sent Slack message to Conrad for the missing links.

**Comment by CrystalSmithwick** [comment]
Clarified what links are missing.

**Comment by CrystalSmithwick** [comment]
Still blocked.  Conrad hasn't responded in Slack.  Assigning back to Ready for draft. 

MISSING LINKS TO INTERNAL ARTICLES.  See comments in article.

**Comment by cjamesbpcs** [comment]
I removed the words that needed a link since godaddy does not have internal articles related to those topics

**Comment by CrystalSmithwick** [comment]
Ok!

Sent from my Windows Phone
________________________________

**Comment by CrystalSmithwick** [comment]
Sorry to send this back one last time.  The image isn't showing up and I can't find the 18228 folder the images or in images folder.

/images/18228/080515/apache-successfully-installed.png

**Comment by cjamesbpcs** [comment]
Gary has added the image to the Github repo, I will move this to code validation and update Susan on the details.

**Comment by susankayjordan** [comment]
Fixed Images and a few code errors  Validated

**Comment by kharise** [comment]
Testing passes. 

Wrote a (brief) Python section.
